name: quizz
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.0
  flutter_local_notifications: ^18.0.0
  vibration: ^3.1.3
  provider: ^6.1.2
  get: ^4.7.2
  intl: ^0.19.0
  audioplayers: ^6.1.0
  html: ^0.15.4
  url_launcher: ^6.2.5
  flutter_animate: ^4.5.0
  confetti: ^0.7.0 # pour ğŸŠ confettis
  lottie: ^2.7.0 # pour animations JSON stylÃ©es

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/gen/
